<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\bgColor.png" />
    <None Remove="assets\bgDark.png" />
    <None Remove="assets\bgWhite.png" />
    <None Remove="assets\icon.png" />
    <None Remove="assets\logo.png" />
    <None Remove="assets\plus.png" />
    <None Remove="assets\profile.png" />
    <None Remove="assets\text.png" />
    <None Remove="assets\x.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\bgColor.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\bgDark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\bgWhite.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\plus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\profile.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\text.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\x.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="assets\movieImages\" />
  </ItemGroup>

</Project>
